import '../../globals.css'
import Provider from '@/SessionProvider'
import { ReduxProvider } from '@/app/globalredux/provider'
import Navbar from '@/components/navbar/Navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({
  children }: { children: React.ReactNode }) {
  return (
    <ReduxProvider>
      <Provider>
        <Navbar />
        {children}
      </Provider>
    </ReduxProvider>
  )
}